### ISSUE TITLE
unable to open database

### ISSUE THREAD

**Issue by ajransaputra** [samthomson/picmap#1]
hy thanks for this dockerfile,im ready tested but when run (docker-compose run picmap bash "picmap/run.sh")
i get error 
Traceback (most recent call last):
  File "./picmap/src/setup.py", line 9, in <module>
    db = sqlite3.connect('/picmap/out/files_database')
sqlite3.OperationalError: unable to open database file

picmap :)
Traceback (most recent call last):
  File "./picmap/src/picmap.py", line 60, in <module>
    db = sqlite3.connect('/picmap/out/files_database')
sqlite3.OperationalError: unable to open database file

can you teach me where im wrong ?

**Comment by samthomson** [comment]
Hi @ajransaputra Thanks for reporting the issue. I'll see if I can reproduce it and post a fix :+1:

**Comment by samthomson** [comment]
Hi @ajransaputra, pull down the latest version and try it again please. I think the issue was that the output directory (`/out`) was git ignored, and so not present when the script wanted to write a db file to it.

If the issue is still unresolved, please re-open this issue, and add any information you can :+1:
